# Generated by Django 5.2 on 2025-04-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserviceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('talla', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Jugador',
            new_name='Usuario',
        ),
        migrations.RemoveField(
            model_name='jugadortorneo',
            name='jugador',
        ),
        migrations.RemoveField(
            model_name='jugadortorneo',
            name='torneo',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='JugadorTorneo',
        ),
        migrations.DeleteModel(
            name='Torneo',
        ),
    ]
