# Generated by Django 5.2 on 2025-05-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserviceapp', '0002_bota_rename_jugador_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='123456789', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='surname',
            field=models.CharField(default='Sin_apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='user_temp', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bota',
            name='talla',
            field=models.CharField(max_length=2),
        ),
    ]
