# Generated by Django 5.2 on 2025-05-27 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webserviceapp', '0003_remove_usuario_id_usuario_password_usuario_surname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre',
            new_name='name',
        ),
    ]
