# Generated by Django 5.2 on 2025-05-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserviceapp', '0004_rename_nombre_usuario_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
