# Generated by Django 5.2 on 2025-05-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserviceapp', '0005_alter_usuario_password_alter_usuario_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
