# Generated by Django 5.2 on 2025-06-05 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserviceapp', '0006_usuario_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='bota',
            name='autor',
            field=models.ForeignKey(default='Christian123', on_delete=django.db.models.deletion.CASCADE, to='webserviceapp.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
