# Generated by Django 5.2 on 2025-06-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserviceapp', '0007_bota_autor_usuario_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinturon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('modelo', models.CharField(max_length=50)),
            ],
        ),
    ]
